### ISSUE TITLE
希望能加上item的点击事件以及item子view的点击事件

### ISSUE THREAD

**Issue by magic0908** [EspoirX/EfficientAdapter#1]
感谢作者提供的思路，我看了下源码，好像是没有处理相关点击事件，希望能添加上

**Comment by EspoirX** [comment]
有的，ViewHolderCreator 这个类里面定义了很多扩展函数来方便对view的使用，里面就有 clicked 和 itemClicked 还有 longClicked 等方法可以处理点击事件，同时也能拿到 itemView ，如果你觉得缺什么方法，也可以自己在里面定义即可。

**Comment by magic0908** [comment]
找到了！不过clicked需要在bindViewHolder方法里使用，但是在列表滚动的过程中onBindViewHolder会被不断调用，那就造成setOnClickListener也会不断调用；如果需要在onCreateViewHolder里就绑定点击事件是否可行呢？

**Comment by EspoirX** [comment]
事实上在正常使用 Adapter 时，item 里面设置点击事件，也是在onBindViewHolder里面设置的吧，这没什么问题。而且你在onCreateViewHolder 里面设置的话，你是拿不到 position 和 data 等信息的。

**Comment by magic0908** [comment]
可以拿到的其实，在onCreateViewHolder方法里创建viewholder的时候，用临时变量记录
val viewHolder = BaseViewHolder
val position = viewHolder.adapterPosition
这样拿到position后，data也能拿到了吧
不过这个看个人需求了吧😉

**Comment by EspoirX** [comment]
这个你可以根据自己的需求进行改造一下
